Nexenta/edgefs

src/ccowhttpd/request.c

Enable ACL set through ccowhttpd

---

deps/corosync/Makefile
deps/fio/Makefile
deps/h2o/Makefile
deps/jemalloc/Makefile
deps/json-c/Makefile
deps/knet/Makefile
deps/libbacktrace/Makefile
deps/liberasurecode/Makefile
deps/libqb/Makefile
deps/libuv/Makefile
deps/lmdb/Makefile
deps/nanomsg/Makefile
deps/nfs-ganesha/Makefile
deps/smartmontools/Makefile
deps/stgt/Makefile

centos flock usage fix

---

src/efscli/efsutil/printmd.go

fixing incorrect check for system object

---

Makefile
deps/fio/Makefile
deps/jemalloc/Makefile
deps/libbacktrace/Makefile
deps/liberasurecode/Makefile
deps/libqb/Makefile
deps/libuv/Makefile
deps/lmdb/Makefile
deps/nanomsg/Makefile
deps/nfs-ganesha/Makefile
deps/smartmontools/Makefile
deps/stgt/Makefile

re #306 enable shallow git modules builds

---

src/corosync-pod-watcher/main.go

corosync-pod watcher didn't create corosync.conf on some setups
fixes #311

Issue #331: a bug in corosync-pod-watcher

---

src/ccow/src/libreptrans/rtrd/reptrans-rd.c
src/ccow/test/Makefile.am

detect deleted/empty meta record for mdcache

---

src/efscli/config/server.go

make sure serverPort is 100 devices apart, do not edit if already set

---

scripts/get-protobuf.sh
src/Makefile
src/corosync-pod-watcher/Makefile
src/efscli/Makefile
src/grpc-efsproxy/Makefile
src/grpc-iscsi/Makefile
src/grpc-nfs/Makefile
src/grpc-s3/Makefile
src/grpc-s3x/Makefile
src/s3gw/Makefile

GOPATH had been located in the target folder. Moved to the build folder.
fixes #318

GOPATH location changed

---

scripts/Makefile
scripts/grpc-proxy-liveness.sh

Signed-off-by: Anton Skriptsov <sabbotagge@gmail.com>
Add grpc-proxy-liveness.sh for mgr pod liveness probe
fixes #
https://github.com/rook/rook/issues/3492

Add grpc-proxy' liveness probe script

---

src/ccow/src/libtrlog/trlog.c

Fixed a bug in  trlog_fetch_tenants(). Sometimes it couldn't find tenants started with TRLOG- and thus, couldn't do bucket insert.
fixes #321

trlog processing: fetch tenants bug

---

src/ccow/src/libccow/acl-list.c
src/ccowhttpd/ccowobj.c
src/ccowhttpd/libauth/auth.c
src/ccowhttpd/libauth/auth.h
src/ccowhttpd/libauth/auth_test.c
src/ccowhttpd/param.c
src/ccowhttpd/param.h
src/ccowhttpd/request_util_test.c
src/ccowhttpd/sig2auth.c
src/ccowhttpd/sig4auth.c
src/grpc-s3x/main.go

Fix s3x auth and acls

---

src/ccowhttpd/ccowobj.c

Fix s3x v4 authentication for put request

---

Dockerfile

Make the Dockerfile working.
fixes #

Dockerfile: make edgefs build in containter be working

---

src/ccowhttpd/request_util.c

Fix s3x core dump on parameter list rescale

---

src/efscli/config/config.go

Follow-up fix for Issue 322
fixes #322

issue-322-followup

---

src/ccowhttpd/ccowhttpd.c
src/ccowhttpd/ccowobj.c
src/ccowhttpd/libauth/Makefile
src/ccowhttpd/libauth/bucket_options.c
src/ccowhttpd/libauth/bucket_options.h
src/ccowhttpd/libauth/json_test.c
src/ccowhttpd/objio.c
src/ccowhttpd/objio.h
src/ccowhttpd/param.c
src/ccowhttpd/param.h
src/ccowhttpd/request_util.c
src/ccowhttpd/session.c
src/ccowhttpd/session.h

Implement s3x objects expiration support

---

src/ccow/src/libreptrans/rtrd/reptrans-rd.c

a copy/past error in dupsort iterator
fixes #

Followup for an iterator fix

---

src/ccow/include/ccow.h
src/ccow/src/libccow/snapview.c
src/efscli/object/snapshot-rollback.go

Added an object's snapshot rollback to the efscli
fixes #346

efscli object snapshot-rollback support

---

src/ccow/src/libtrlog/trlog.c

SOP trlog followup fix

---

src/ccow/src/libflexhash/flexhash.c
src/ccow/src/libtrlog/trlog.c

Followup fixes for SOP trlog

---

src/ccow/src/libccowd/trput.c

TRLOG extra errors output

---

src/ccow/src/libccow/named-get.c

Bypass bucket objects in chunk recovery flow

---

src/ccow/src/libccow/ccow-impl.h
src/ccow/src/libreptrans/rtrd/reptrans-rd.c

Reduce ccowd memory footprint

---

src/ccow/src/libreptrans/reptrans.c

GC background change: skip a parent lookup in a split
fixes #

GC background change: skip a parent lookup in split

---

src/ccow/src/libccowfsio/fsio_inode.c
src/ccow/src/libccowfsio/fsio_system.c
src/ccow/src/libccowfsio/include/fsio_system.h

Enable select_policy inhereting

---

src/efscli/system/status.go

Add separate line for segment id to efscli system summary

---

Dockerfile
src/ccow/src/libreptrans/rtkvs/kvs-backend.h
src/ccow/src/libreptrans/rtkvs/reptrans-kvs.c
src/efscli/config/config.go
src/efscli/config/layout.go

Some changes to rtkvs and efscli for further k8s and rook support
fixes #

RTKVS: preparation work for k8s and rook

---

.gitmodules
Dockerfile
deps/Makefile
deps/kvssd/Makefile
src/ccow/.gitignore
src/ccow/src/libreptrans/configure.ac.m4
src/ccow/src/libreptrans/rtkvs/Makefile.am
src/ccow/src/libreptrans/rtkvs/backend/kvssd/Makefile.am
src/ccow/src/libreptrans/rtkvs/backend/kvssd/kvssd-backend.c
src/ccow/src/libreptrans/rtkvs/reptrans-kvs.c
src/ccow/test/Makefile.am
src/ccow/test/kvssd_backend_test.c

Initial support for Samsung KVSSD
fixes #358

Added  initial support for Samsung's KV SSD devices

---

src/ccow/include/ccow.h
src/ccow/src/libccow/ccow-impl.h
src/ccow/src/libccow/ccow.c
src/ccow/src/libchunk/cmcache.c
src/ccow/src/libreptrans/getcommon_server.c
src/ccow/src/libreptrans/named-put.c
src/ccow/src/libreptrans/reptrans.c
src/ccow/src/libreptrans/rtkvs/reptrans-kvs.c
src/ccow/src/libreptrans/unnamed-put.c
src/ccow/src/libreptrans/verify.c
src/efscli/config/config.go

A number of performance fixes and related bugfixes in ccow's caches
fixes #

Ccow cache fixes

---

src/ccow/src/libccow/ccow-impl.h
src/ccow/src/libccow/put.c
src/ccow/src/libccow/sharded-list.c
src/ccow/src/libreptrans/serial_op.c
src/ccow/test/basic_fs_ops_test.c

Fix SOP sharded list attributes processing

---

src/ccow/src/libccowd/trput.c

Fix object expunge transaction log flow

---

src/ccow/src/libchunk/btree/libbtreenam/btreenam.c

This is a follow-up fix for bucket snapshot with which should fix a regression in the SOP.
fixes #

btreenam: SOP fix

---

src/ccow/include/ccow.h
src/ccow/src/libccow/put.c
src/ccow/src/libccow/snapview.c
src/ccow/src/libccowfsio/fsio_inode.c
src/ccow/test/clone_test.c
src/ccow/test/put_file.c
src/ccow/test/versions_test.c

reverted copy_opts.version_vm_content_hash_id

---

src/efscli/cluster/create.go

A fix for issue #377
fixes #377

Prevent creation of a cluster if system isn't initialized

---

src/ccow/src/libccow/ccow-dynamic-fetch.c
src/ccow/src/libccow/ccow-dynamic-fetch.h
src/ccow/src/libccow/unnamed-get.c

Pass segment id to isgw service

---

src/ccow/src/libccow/unnamed-get.c

Allow unnamed get for VM of a deleted object if it's requested by an ISGW
fixes #401

A delete VM get fix

---

src/ccow/include/ccowutil.h
src/ccow/src/libccowfsio/Makefile.am
src/ccow/src/libccowfsio/fsio_inode.c
src/ccow/src/libccowfsio/fsio_listcache.c
src/ccow/src/libccowfsio/fsio_namespace.c
src/ccow/src/libccowfsio/fsio_s3_transparency.c
src/ccow/src/libccowfsio/fsio_s3cache.c
src/ccow/src/libccowfsio/fsio_s3cache.h
src/ccow/src/libccowfsio/fsio_system.c
src/ccow/src/libccowfsio/include/fsio_inode.h
src/ccow/src/libccowfsio/include/fsio_s3_transparency.h
src/ccow/src/libccowfsio/include/fsio_system.h

Add listing cache for nfs listings of s3 objects

---

src/ccow/src/libccow/getcommon_client.h

- [* ] Change is code complete and matches issue description.
- [ *] Change is covered by existing or new tests.
REPLIES_CNT() subtracts 2 from sync_put_named. Hence it should check if it's greater than 1.
fixes #394

REPLIES_CNT() should check if sync_put_named is greater than 1.

---

src/efscli/config/config.go

- [ *] Change is code complete and matches issue description.
- [ *] Change is covered by existing or new tests.
Extract the node name out of CNAME
Do we need node name or FQDN.
If we need FQDN then we need to remove only the last character "."
fixes #409

Extract nodename out of CNAME. Drop "."

---

src/ccow/src/libccowfsio/fsio_namespace.c

Followup fix for nfs listings of s3 objects

---

src/ccowhttpd/ccowhttpd.c

Decrease ccowhttpd stack size to 16M

---

src/ccow/src/libreptrans/ngrequest-send.c
src/ccow/src/libreptrans/reptrans.c

Added an extended error logging in order to identify the problem source
fixes #

More verbosity for VBR replication errors

---

src/ccow/src/libccow/unnamed-get.c

A delete VM get reflist fix

---

src/ccow/src/libccow/named-put.c
src/ccow/src/libreptrans/Makefile.am
src/ccow/src/libreptrans/payload-s3.c
src/ccow/src/libreptrans/payload-s3.h
src/ccow/src/libreptrans/reptrans-device.h
src/ccow/src/libreptrans/reptrans.c
src/ccow/src/libreptrans/reptrans.h
src/ccow/src/libreptrans/rtlfs/Makefile.am
src/ccow/src/libreptrans/rtlfs/reptrans-lfs.c
src/ccow/src/libreptrans/rtrd/reptrans-rd.c
src/ccow/src/libreptrans/rtrd/reptrans-rd.h
src/ccow/src/libreptrans/unnamed-put.c
src/ccow/tools/dbi_util.c
src/efscli/config/layout.go

1. S3 Payload support for RTRD
2. Bug in RTRD: the WAL isn't flushing at the start that leads to a broken bloom filter
3. Bug in EC clone
fixes #422

Rtrd s3offload

---

src/ccow/src/libreptrans/rtrd/reptrans-rd.c

Fixed a typo in RTRD
fixes #426

issue-426: disable rdhold in Docker

---

src/ccow/src/libreptrans/unnamed-put.c

S3-offload followup fix

---

src/ccow/include/ccowfsio.h
src/ccow/src/libccowfsio/fsio_file.c
src/ccow/src/libccowfsio/fsio_flusher.c
src/ccow/src/libccowfsio/fsio_inode.c
src/ccow/src/libccowfsio/include/fsio_inode.h

Fix NFS to pickup updates from remote site

---

src/ccow/src/libccowfsio/fsio_namespace.c

Fix NFS objects list flow

---

src/ccow/src/libreptrans/rtrd/reptrans-rd.c

RTRD initialization fix: wait for device/journal symlinks
fixes #439

RTRD init: wait for journal/device symlinks for 10 sec before reporting an error

---

src/ccow/src/libccow/putcommon_client.c

Ignore sync_put option for key/value objects

---

src/efscli/service/delete.go
src/grpc-efsproxy/Makefile
src/grpc-efsproxy/cluster/cluster.proto
src/grpc-efsproxy/cluster/clusterImpl/cluster.go
src/grpc-efsproxy/efsutil/efsutil.go
src/grpc-efsproxy/main.go
src/grpc-efsproxy/service/service.proto
src/grpc-efsproxy/service/serviceImpl/service.go
src/grpc-efsproxy/tenant/bucketImpl/bucket.go
src/grpc-efsproxy/tenant/tenant.proto
src/grpc-efsproxy/tenant/tenantImpl/tenant.go
src/grpc-efsproxy/tenant/userImpl/user.go

Extend grpc-proxy service to support cluster and user create requests

---

src/grpc-efsproxy/efsutil/attributes.go
src/grpc-efsproxy/efsutil/mdutil.go
src/grpc-efsproxy/efsutil/updatemd.go
src/grpc-efsproxy/efsutil/user.go

Followup fix for grpc-efsproxy

---

src/grpc-efsproxy/cluster/cluster.proto
src/grpc-efsproxy/cluster/clusterImpl/cluster.go
src/grpc-efsproxy/efsutil/kvutil.go
src/grpc-efsproxy/service/service.proto
src/grpc-efsproxy/service/serviceImpl/service.go
src/grpc-efsproxy/tenant/bucketImpl/bucket.go
src/grpc-efsproxy/tenant/tenant.proto
src/grpc-efsproxy/tenant/tenantImpl/tenant.go

Add show methods to grpc-efsproxy service

---

src/ccow/src/libccow/getcommon_client.c
src/ccow/src/libreptrans/rtrd/reptrans-rd.c
src/ccow/src/libreptrans/rtrd/reptrans-rd.h
src/ccow/test/reptrans_standalone_test.c

RTRD: put latency jitter fix

---

src/ccow/src/libccowfsio/fsio_flusher.c

Free bufferes after file flush. Reduce memory usage by NFS service.

---

src/ccow/src/libauditd/auditd.c
src/ccow/src/libccowfsio/fsio_flusher.c

warning fixes

---

src/ccow/src/libccow/ccow-impl.h
src/ccow/src/libccow/putcommon_client.c
src/ccow/src/libccow/unnamed-put.c
src/ccow/src/libccowfsio/fsio_inode.c
src/ccow/src/libreptrans/payload-s3.c
src/ccow/src/libreptrans/payload-s3.h
src/ccow/src/libreptrans/rtrd/reptrans-rd.c
src/ccow/test/reptrans_standalone_test.c

RTRD over S3: parallel delete support

---

.gitmodules
Makefile
deps/Makefile
deps/dqlite/.gitignore
deps/dqlite/Makefile
deps/libco/.gitignore
deps/libco/Makefile
deps/raft/.gitignore
deps/raft/Makefile
deps/sqlite/.gitignore
deps/sqlite/Makefile
src/Makefile
src/ccow/include/ccowfsio.h
src/ccow/include/ccowutil.h
src/ccow/src/libccowfsio/fsio_cache.c
src/ccow/src/libccowfsio/fsio_file.c
src/ccow/src/libccowfsio/include/fsio_inode.h
src/ccow/src/libreptrans/reptrans.h
src/ccownbd/ccownbd.c
src/dqlite/Makefile
src/dqlite/dqlite.c
src/efscli/service/create.go
src/efscli/service/serve.go
src/efscli/validate/validate.go
src/grpc-sql/.gitignore
src/grpc-sql/Makefile
src/grpc-sql/main.go

this implements dqlite integration where raft logs stored directly in EdgeFS fabric.
for reviews only
fixes #404

Dqlite integration

---

deps/libco/Makefile
src/ccow/src/libccowfsio/fsio_cache.c
src/ccow/src/libccowfsio/include/fsio_disk.h

improve writes parallelism

---

src/ccow/src/libreptrans/rtrd/reptrans-rd.c

RTRD: use WAL only for payloads in S3 offload mode

---

src/ccow/src/libconnbroker/connbroker.c
src/ccow/src/libconnbroker/connbroker.h
src/ccow/src/libconnbroker/replicast_broker.c

Set connection broker keepalive timeout

---

src/ccow/src/libccow/opp-status.c
src/ccow/src/libccow/opp-status.h
src/ccow/src/libclengine/clengine.c
src/ccow/src/libreplicast/replicast.c
src/ccow/src/libreplicast/replicast.h
src/ccow/src/libreptrans/opp-status-srv.c
src/ccow/src/libreptrans/reptrans.c
src/ccow/src/libreptrans/rtrd/reptrans-rd.c
src/ccow/src/libreptrans/rtrd/reptrans-rd.h
src/ccow/tools/ecstat.c

1. Fixed a bub in the blobfind tool
2. The ecstat tool supports NFS objects validation
3. Fixed a bug in RTRD (S3 payload)
fixes #

Ecstat nfs support

---

src/efscli/system/status.go

Fix efscli summary counts

---

src/ccow/src/libccowfsio/fsio_cache.c

fixes #
Suggested by: dyusupov

Disable cache for read in CCOW FSIO. Data already cached by CCOW.

---

.gitmodules

Integrate latest corosync bug fixes.
fixes #309

corosync update to v3.0.3

---

src/dqlite/Makefile
src/dqlite/dqlite.c
src/dqlite/libdqclient/Makefile
src/dqlite/libdqclient/dqclient.c
src/dqlite/libdqclient/dqclient.h
src/dqlite/libdqclient/test_client.c
src/grpc-sql/main.go

code.
- [ *] Change is code complete and matches issue description.
- [ *] Change is covered by existing or new tests.
Added code to edgefs, deps/dqlite/dqlite to:
1. Added code to join the cluster
2. Added code to leave the cluster
3. Added code to get leader server
4. Added code to list cluster servers
5. Made changes to grpc-sql that will form cluster
fixes #

Added code to list cluster, leader as well as to join and leave the

---

src/efscli/config/config.go

Corosync mtu: fixed

---

src/ccow/tools/ecstat.c

Fixed a bug in ecstat NFS bucket iterator
fixes #

ecstat tool: NFS bucket iterator fix

---

src/ccow/test/sharded_list_basic_fs_dir_test.c

follow up fix for sharded_list_basic_fs_dir_test.c

---

src/ccow/src/libccowfsio/fsio_file.c
src/dqlite/dqlite.c
src/dqlite/libdqclient/Makefile
src/dqlite/libdqclient/stress_test.c

- [* ] Change is code complete and matches issue description.
Stress test for ccow-sql
fixes #

Added stress test for DSQL.

---

src/ccow/src/libchunk/btree/libbtreecommon/btreecom.c

Fix modbit for partial update

---

src/dqlite/libdqclient/Makefile
src/dqlite/libdqclient/geolock.c
src/dqlite/libdqclient/geolock.h
src/dqlite/libdqclient/test_geolock.c

- [ *] Change is code complete and matches issue description.
- [ *] Change is covered by existing or new tests.
Implemented global lock APIs. New test added.
fixes #

Issue 503 - dqlite global lock

---

src/ccow/include/glm_ops.h
src/ccow/src/libccowfsio/Makefile.am
src/ccow/src/libccowfsio/fsio_glm.c
src/ccow/src/libccowfsio/fsio_inode.c
src/ccow/src/libccowfsio/fsio_system.c
src/ccow/src/libccowfsio/include/fsio_inode.h
src/ccow/src/libccowfsio/include/fsio_system.h
src/dqlite/Makefile
src/dqlite/libdqclient/Makefile
src/dqlite/libdqclient/glm_dqlite.c

- [*] Change is code complete and matches issue description.
- [*] Change is covered by existing or new tests.
1. /opt/edgefs/scripts/edgefs-start.sh solo
2. ccow-sql -i 1 -a 127.0.0.1:9181 -d cltest/test/bk1/1 -o "1,127.0.0.1:9181;2,127.0.0.1:9182;3,127.0.0.1:9183"
3. ccow-sql -i 2 -a 127.0.0.1:9182 -d cltest/test/bk1/2 -o "1,127.0.0.1:9181;2,127.0.0.1:9182;3,127.0.0.1:9183"
4. ccow-sql -i 3 -a 127.0.0.1:9183 -d cltest/test/bk1/3 -o "1,127.0.0.1:9181;2,127.0.0.1:9182;3,127.0.0.1:9183"
5. export CCOW_GEOLOCK_SERVICE=mydb
6. basic_fs_inodefetch_test
fixes #513

Added geolocking functionality to NFS.

---

src/ccow/include/ccowfsio.h
src/ccow/src/libccow/bucket-delete.c
src/ccow/src/libccowd/trput.c
src/ccow/src/libccowfsio/fsio_flusher.c
src/ccow/src/libccowfsio/fsio_system.c
src/ccow/src/libccowfsio/include/fsio_system.h

Fix multicluster NFS stats

---

src/ccow/include/glm_ops.h
src/ccow/src/libccowfsio/fsio_glm.c
src/dqlite/libdqclient/glm_dqlite.c

- [*] Change is code complete and matches issue description.
- [*] Change is covered by existing or new tests.
Some fixes to geo-locking.
fixes #
#517

Geo-locking changes/fixes.

---

Makefile
deps/samba/Makefile

build fix followup

---

deps/samba/Makefile
deps/samba/README.md
deps/samba/smb.conf
deps/samba/test-bk.conf
scripts/edgefs-start.sh
src/Makefile
src/efscli/bucket/delete.go
src/efscli/efsutil/attributes.go
src/efscli/service/create.go
src/efscli/service/serve.go
src/efscli/service/service.go
src/efscli/service/unserve.go
src/efscli/validate/validate.go
src/grpc-smb/.gitignore
src/grpc-smb/Makefile
src/grpc-smb/export/export.go
src/grpc-smb/export/export.proto
src/grpc-smb/main.go

deep smb integration

---

src/ccow/src/libreptrans/reptrans.c

Bug in chunk replication scheduling code.
fixes #

libreptrans: replication on ERC error fix

---

deps/samba/Makefile
scripts/edgefs-start.sh
src/grpc-nfs/export/export.go
src/grpc-smb/export/export.go

fix for X-SMB-OPTS setting

---

src/ccow/src/libccow/opp-status.h
src/ccow/src/libreptrans/opp-status-srv.c
src/ccow/tools/ecstat.c

the ecstat tool got a number of changes for a better user experience
fixes #

ecstat updated

---

deps/samba/Makefile
deps/samba/ads-join.sh
deps/samba/smb.conf
src/grpc-smb/main.go

smb: ads join plumbing

---

deps/samba/Makefile
src/grpc-smb/main.go

smb: added winbindd

---

deps/samba/Makefile
deps/samba/ads-join.sh

smb: added nss libs

---

deps/samba/ads-join.sh
deps/samba/smb.conf
src/grpc-smb/main.go

smb: ability to enable debug while joining AD

---

src/ccow/src/libccowfsio/fsio_glm.c
src/efscli/service/serve.go
src/efscli/service/unserve.go
src/efscli/validate/validate.go
src/grpc-sql/main.go

2. Added unserve for dsql
3. Fixed code to process the new configuration
fixes #

1. Fixed dsql service to configure for a cluster (few nodes)

---

deps/samba/Makefile
deps/samba/ads-join.sh
deps/samba/smb.conf
src/grpc-smb/main.go

smb: AD join fixes

---

src/ccow/include/ccow.h
src/ccow/include/glm_ops.h
src/ccow/src/libccow/ccow.c
src/ccow/src/libccow/sharded-list.c
src/ccow/src/libccowfsio/fsio_dir.c
src/ccow/src/libccowfsio/fsio_disk.c
src/ccow/src/libccowfsio/fsio_glm.c
src/ccow/src/libccowfsio/fsio_inode.c
src/ccow/src/libccowfsio/fsio_listcache.c
src/ccow/src/libccowfsio/fsio_listcache.h
src/ccow/src/libccowfsio/fsio_recovery.c
src/ccow/src/libccowfsio/fsio_snapshot.c
src/ccow/src/libccowfsio/fsio_system.c
src/ccow/src/libccowfsio/include/fsio_inode.h
src/ccow/src/libccowfsio/include/fsio_system.h
src/dqlite/Makefile
src/dqlite/dqlite.c
src/dqlite/libdqclient/Makefile
src/dqlite/libdqclient/dqclient.c
src/dqlite/libdqclient/dqclient.h
src/dqlite/libdqclient/geolock.c
src/dqlite/libdqclient/geolock.h
src/dqlite/libdqclient/glm_dqlite.c
src/dqlite/libdqclient/list_geolock.c
src/dqlite/libdqclient/test_client.c
src/dqlite/libdqclient/test_geolock.c

Implement multicluster NFS sync

---

src/dqlite/libdqclient/Makefile
src/dqlite/libdqclient/glm_dqlite.c

NFS sync followup fix

---

src/ccow/src/libccowfsio/fsio_disk.c

NFS sync foolowup fix 2

---

src/efscli/efsutil/kvutil.go
src/efscli/service/serve.go
src/grpc-sql/main.go

grpc-sql: rook integration fixes

---

src/grpc-nfs/main.go
src/grpc-smb/main.go

glm: propagate rook setting to smb and nfs

---

src/dqlite/dqlite.c
src/grpc-sql/main.go

followup fixes part2
